import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' className={` h-full antialiased`}>
      <body className='min-h-ful bg-gray-50 '>
        <Navbar />
        <main className='container mx-auto px-4 py-8'>{children}</main>
      </body>
    </html>
  );
}
